name: Gatsby Build Manually

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.3.1

    - name: Install dependencies
      run: npm install

    - name: Build Gatsby App
      run: npm run deploy